### ISSUE TITLE
What about include worldwide companies?

### ISSUE THREAD

**Issue by juanbrujo** [matildaexp/remote-latam#5]
Some companies in Europe also open positions for LATAM, what about to expando not for only US-bases companies?

**Comment by muZk** [comment]
Good Idea 😄

Worldwide is okay, the only requirement is that the companies should offer something challenging to find in the local market. Example:

- Above the market salaries: thinking about 80k+ yearly salary.
- Market salary but with cool benefits, like 4-day workweeks or unlimited PTO.

That's why I haven't added some companies of #2, I think some of them don't fulfil those requirements
